version: '3'
services:
  rabbitmqhackathon:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmqhackathon'
    restart: unless-stopped
    command: "/bin/bash -c \"rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_mqtt rabbitmq_amqp1_0; rabbitmq-server\""
    hostname: 'rabbitmqhackathon'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "1883:1883"
      - "8883:8883"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  object-detection-service:
    build: ./objectDetectionAiService
    restart: on-failure
    depends_on:
      - rabbitmqhackathon
  facial-expression-service:
    build: ./facialExpressionAiService
    restart: on-failure
    depends_on:
      - rabbitmqhackathon
  image-retriever-service:
    build: ./imageRetrieverService
    restart: on-failure
    ports:
      - "4000:4000"
    depends_on:
      - rabbitmqhackathon
  frontend-service:
    build: ./frontendService
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmqhackathon